Implementing changes from Matrix project.
CluedIn-io/CluedIn.Connector.PowerBI pull request #3
Opened 2021-12-23 18:33 UTC by DmytroLohvynenko

Ref https://github.com/CluedIn-io/CluedIn.Connector.Matrix/issues/98

Some test setup code was disabled.

2022-01-13 04:59 UTC, andrew-hardy requested changes

2022-01-13 04:59 UTC, andrew-hardy commented on src/Connector.PowerBI/Connector/PowerBIConnector.cs
> +                // TODO: Check the table is sended correctly
Has this TODO been done? If so please remove it

2022-01-13 04:59 UTC, andrew-hardy commented on src/Connector.PowerBI/Connector/PowerBIConnector.cs
> +            throw new NotImplementedException();
Should this be implemented?

2022-01-13 04:59 UTC, andrew-hardy commented on test/unit/Connector.PowerBI.Test/TestContext.cs
> +            //OrganizationRepository.Setup(r => r.GetOrganization(It.IsAny<ExecutionContext>(), It.IsAny<Guid>())).Returns<ExecutionContext, Guid>((c, i) => OrganizationFactory(c, i));
Please uncomment this and fix test if required

2022-01-13 17:22 UTC, DmytroLohvynenko commented on src/Connector.PowerBI/Connector/PowerBIConnector.cs
> +            throw new NotImplementedException();
before it was mocked to always return `true`. 
Unfortunately we haven't had enough time and PowerBI account to test this connector.

2022-01-13 17:56 UTC, DmytroLohvynenko commented on test/unit/Connector.PowerBI.Test/TestContext.cs
> +            //OrganizationRepository.Setup(r => r.GetOrganization(It.IsAny<ExecutionContext>(), It.IsAny<Guid>())).Returns<ExecutionContext, Guid>((c, i) => OrganizationFactory(c, i));
there are no active tests in the solution <>
This was some kind of test setup, but actually not used anywhere (or I can't find a place where it is used).
So just removed it.

2022-01-13 18:07 UTC, DmytroLohvynenko commented on src/Connector.PowerBI/Connector/PowerBIConnector.cs
> +                // TODO: Check the table is sended correctly
Probably the same as in other case.
It was added, but connector wasn't in priority to check.

2022-01-14 12:32 UTC, DmytroLohvynenko commented on src/Connector.PowerBI/Connector/PowerBIConnector.cs
> +            throw new NotImplementedException();
returned mocked version, now always return `true`.

2022-01-14 12:33 UTC, DmytroLohvynenko commented on src/Connector.PowerBI/Connector/PowerBIConnector.cs
> +                // TODO: Check the table is sended correctly
removed TODO comment.

2022-01-14 12:34 UTC, romaklimenko approved these changes

2022-01-16 23:13 UTC, andrew-hardy approved these changes

2022-01-16 23:13 UTC, merged